### ISSUE TITLE
Data cap bandwidth monitoring?

### ISSUE THREAD

**Issue by AsianDesignMajor** [ViktorJp/RTRMON#1]
Thanks for your efforts!

Without screenshots, I don't know if RTRMON shows total WAN data consumed per month or not - does it?  

Xfinity has a 1.2TB data cap and I will never turn on the Trend Micro stuff, so I'm looking for a way to monitor my monthly bandwidth usage within Merlin.

I'm currently rocking 386.9 on an AC68U.

**Comment by ViktorJp** [comment]
Much appreciated, @AsianDesignMajor  ;)

I have some screenshots located here on the [SNB Forums](https://www.snbforums.com/threads/rtrmon-v1-54-jan-03-2023-monitor-your-routers-health-new-amtm-network-conn-bandwidth-diag-port-scanner-gt-axe-ax-compatibility-speedtest.79738/)

But no, it does not track accumulated WAN data over the month.  It's more real-time averages.  If you're running Asus-Merlin firmware, there are some options there for you to track this... You might want to check out vnStat - it gives you a graphical UI that shows you the daily/weekly/monthly/yearly bandwidth consumed: [vnStat](https://www.snbforums.com/threads/release-vnstat-on-merlin-ui-cli-and-email-data-use-and-data-limit-monitoring-r1-and-r2.71523/)

There is also a built-in traffic analyzer in the Asus-Merlin UI that will be able to report on bandwidth consumed over the month.   But the Xfinity site also shows your monthly bandwidth consumed as well when you log into your account.  We ended up paying extra because we would always hit that 1.2Gb limit, and wasn't worth paying the fines for going over.

Let me know if I can help with anything else, K?
